@startuml
skinparam shadowing false
skinparam backgroundColor white
skinparam fontName Times New Roman
skinparam sequenceMessageAlign left
skinparam sequenceArrowColor black
skinparam sequenceLifeLineBorderColor black
title Biểu đồ tuần tự chức năng đăng nhập

actor "Người dùng" as User
boundary "Giao diện\nđăng nhập" as UI
control "Hệ thống xử lý" as Sys
database "CSDL\nusers" as DB

User -> UI : 1. Nhập email/mật khẩu
UI -> Sys : 2. Gửi yêu cầu đăng nhập
Sys -> Sys : 3. Kiểm tra thông tin
Sys -> DB : 4. Truy vấn thông tin
DB --> Sys : 5. Trả kết quả về
Sys --> UI : 6. Xác nhận đăng nhập\nthành công
UI --> User : 7. Hiển thị thông báo\nđăng nhập thành công
@enduml
