@startuml
skinparam shadowing false
skinparam backgroundColor white
skinparam fontName Times New Roman
skinparam sequenceMessageAlign left
skinparam sequenceArrowColor black
skinparam sequenceLifeLineBorderColor black
title Biểu đồ tuần tự chức năng đăng ký

actor "Khách vãng lai" as User
boundary "Giao diện\nđăng ký" as UI
control "Hệ thống xử lý" as Sys
database "CSDL\nusers" as DB

User -> UI : 1. Nhập họ tên, email,\nmật khẩu
UI -> Sys : 2. Gửi yêu cầu đăng ký
Sys -> Sys : 3. Kiểm tra dữ liệu
Sys -> DB : 4. Lưu tài khoản
DB --> Sys : 5. Trả kết quả về
Sys --> UI : 6. Gửi mã xác thực email
UI --> User : 7. Hiển thị màn hình\nnhập mã
@enduml
