@startuml
skinparam shadowing false
skinparam backgroundColor white
skinparam fontName Times New Roman
skinparam activityBackgroundColor white
skinparam activityBorderColor black
skinparam activityDiamondBackgroundColor white
skinparam activityDiamondBorderColor black
skinparam activityStartColor black
skinparam activityEndColor black
title Sơ đồ hoạt động chức năng thanh toán

|Người dùng|
start
:Nhập địa chỉ nhận hàng;
:Chọn COD hoặc MoMo;
:Xác nhận;

|Hệ thống|
:Kiểm tra thông tin và phí ship;
if (Kiểm tra) then (Đúng)
  :Tạo đơn hàng;
  :Báo đặt hàng thành công;
else (Sai)
  :Báo lỗi;
endif
stop
@enduml
