[relic-login]
enabled = true
filter = relic-login
logpath = /var/www/html/storage/logs/relic-auth.log
maxretry = 5
findtime = 600
bantime = 900
port = http,https
action = iptables-multiport[name=relic-login, port="http,https", protocol=tcp]
